modLoader="javafml"
loaderVersion="[46,)"
license="All Rights Reserved"

[[mods]]
modId="puffish_skills"
version="${version}"
displayName="Pufferfish's Skills"
authors="Pufferfish"
description="Adds a fully configurable skill system to the game."

[[dependencies.puffish_skills]]
modId="forge"
mandatory=true
versionRange="[46,)"
ordering="NONE"
side="BOTH"

[[dependencies.puffish_skills]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"
