modLoader="javafml"
loaderVersion="[2,)"
license="All Rights Reserved"

[[mixins]]
config = "puffish_skills.mixins.json"

[[mods]]
modId="puffish_skills"
version="${version}"
displayName="Pufferfish's Skills"
authors="Pufferfish"
description="Adds a fully configurable skill system to the game."

[[dependencies.puffish_skills]]
modId="neoforge"
type="required"
versionRange="[20.4,)"
ordering="NONE"
side="BOTH"

[[dependencies.puffish_skills]]
modId="minecraft"
type="required"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
